{
  "on": {
    "release": {
      "types": [
        "created"
      ]
    }
  },
  "jobs": {
    "pypi": {
      "steps": [
        {
          "name": "fetch all history and tags",
          "uses": "actions/checkout@v2",
          "with": {
            "fetch-depth": 0
          }
        },
        {
          "name": "setup python",
          "uses": "actions/setup-python@v2",
          "with": {
            "python-version": "${{ matrix.python-version}}"
          }
        },
        {
          "name": "upgrade dependencies",
          "run": "python -m pip install --upgrade pip nox"
        },
        {
          "name": "test within nox",
          "run": "nox -s test"
        }
      ],
      "strategy": {
        "matrix": {
          "python-version": [
            3.8,
            3.9
          ]
        }
      },
      "runs-on": "ubuntu-latest"
    }
  }
}