{
  "on": {
    "release": {
      "types": [
        "created"
      ]
    }
  },
  "jobs": {
    "pypi": {
      "steps": [
        {
          "name": "setup python",
          "uses": "actions/setup-python@v2",
          "with": {
            "python-version": 3.9
          }
        },
        {
          "name": "fetch all history and tags",
          "uses": "actions/checkout@v2",
          "with": {
            "fetch-depth": 0
          }
        },
        {
          "name": "upgrade dependencies",
          "run": "python -m pip install --upgrade pip build setuptools wheel"
        },
        {
          "name": "build python",
          "run": "python -m build --sdist --wheel"
        },
        {
          "name": "publish",
          "uses": "pypa/gh-action-pypi-publish@master",
          "with": {
            "user": "docfast",
            "password": "${{ secrets.pypi_password }}"
          }
        }
      ],
      "strategy": {},
      "runs-on": "ubuntu-latest"
    }
  }
}